
// This file is no longer used manually.
// The Service Worker is now generated by vite-plugin-pwa during the build process.
// Please run `npm run build` to generate the correct sw.js in the dist/ folder.
